version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=my-vpn.example.com
      - PASSWORD=<YOUR-SECURE-PASSWORD>
      - WG_PORT=51820
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      caddy: my-vpn.example.com
      caddy.reverse_proxy: "{{upstreams 51821}}"
    networks:
      - caddy
      - wg

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true
  wg:

volumes:
  caddy_data: {}